export const tourList = [
  {
    id: 1,
    city: 'new york',
    img: './img/new york bridge.jpg',
    name: 'new york bridge',
    info: '',
  },
  {
    id: 2,
    city: 'paris',
    img: './img/paris light.jpg',
    name: ' Eiffel Tower',
    info: ' it consists of 336 projectors equipped with high-pressure, yellow-orange sodium lampsThis form of illumination, which has been met with unanimous, worldwide success, was the starting point of a nocturnal revival of monuments, in Paris as well as in the cities of France and the world.',
  },
  {
    id: 3,
    city: 'london',
    img: './img/Buckingham-palace.jpg',
    name: 'london royal palace',
    info: 'Buckingham Palace is a must-see when it comes to Royal Palaces in London. With 775 rooms along with the most extensive private garden in London, it is the Queen’s official London residence and a working royal palace..',
  },
  {
    id: 4,
    city: 'cambodia',
    img: './img/ambodia-angkor-wat-stone-faces.jpg',
    name: 'angkor wat stone faces',
    info: ' Over 200 giant smiling faces remain, but there may once have been between one and two hundred towers, each with four faces. These structures are known as "face towers." The bas-relief carvings on the outer walls of the Bayon towers depict heroic historical tales as well as scenes of everyday Khmer life.',
  },
  {
    id: 5,
    city: 'london',
    img: './img/arizona-grand-canyon.jpg',
    name: 'grand canyon',
    info: ' Grand Canyon National Park, in Arizona, is home to much of the immense Grand Canyon, with its layered bands of red rock revealing millions of years of geological history. Viewpoints include Mather Point, Yavapai Observation Station and architect Mary Colter’s Lookout Studio and her Desert View Watchtower.',
  },
  {
    id: 6,
    city: 'canada/United State',
    img: './img/canada-united-states-niagara-falls.jpg',
    name: 'niagara falls',
    info: ' Niagara Falls, Ontario, is a Canadian city at the famous waterfalls of the same name, linked with the U.S. by the Rainbow Bridge. Its site on the Niagara Rivers western shore overlooks the Horseshoe Falls, the cascades most expansive section. ',
  },
  {
    id: 7,
    city: 'united State',
    img: './img/canyon-snow-us.jpg',
    name: 'cayon snow',
    info: ' Snow Canyon State Park is a state park in Utah, located in the Red Cliffs Desert Reserve.[1] The park features a canyon carved from the red and white Navajo sandstone of the Red Mountains, as well as the extinct Santa Clara Volcano, lava tubes, lava flows, and sand dunes. Snow Canyon is located near the cities of Ivins.',
  },
  {
    id: 8,
    city: 'New york',
    img: './img/central-park-new-york-city.jpg',
    name: 'central park',
    info: 'Central Park is an urban park in New York City, between the Upper West and Upper East Sides of Manhattan. It is the fifth largest park in the city, covering 843 acres.',
  },
  {
    id: 9,
    city: 'france',
    img: './img/chateau-versailles-france.jpg',
    name: 'chateau versailles',
    info: '  A former royal residence located in Versailles, about 12 miles (19 km) west of Paris, France. The palace is owned by the French Republic and has since 1995 been managed, under the direction of the French Ministry of Culture, by the Public Establishment of the Palace.',
  },
  {
    id: 10,
    city: 'mexico',
    img: './img/chichen-itza-mexico.jpg',
    name: 'chichen itza',
    info: ' The site exhibits a multitude of architectural styles, reminiscent of styles seen in central Mexico and of the Puuc and Chenes styles of the Northern Maya lowlands. The presence of central Mexican styles was once thought to have been representative of direct migration or even conquest from  Mexico.',
  },
  {
    id: 11,
    city: 'china',
    img: './img/china-forbidden-city.jpg',
    name: 'forbidden city',
    info: 'The Forbidden City was the political and ritual center of China for over 500 years. After its completion in 1420, the Forbidden City was home to 24 emperors, their families and servants during the Ming (1368–1644) and the Qing (1644–1911) dynasties. The last occupant, Puyi (1906–67).',
  },
  {
    id: 12,
    city: 'china',
    img: './img/china-great-wall.jpg',
    name: 'great wall',
    info: '  a series of fortifications that were built across the historical northern borders of ancient Chinese states and Imperial China as protection against various nomadic groups from the Eurasian Steppe. Several walls were built from as early as the 7th century BC,[4] with selective stretches later joined together by Qin Shi Huang (220–206 BC), ',
  },
  {
    id: 13,
    city: 'corcovado',
    img: './img/corcovado-cristo-redentor-rio-de-janeiro.jpg',
    name: 'Christ_the_Redeemer_-_Cristo_Redentor',
    info: 'Art Deco statue of Jesus Christ in Rio de Janeiro, Brazil, created by French sculptor Paul Landowski and built by Brazilian engineer Heitor da Silva Costa, in collaboration with French engineer Albert Caquot. Romanian sculptor Gheorghe Leonida fashioned the face. .',
  },
  {
    id: 14,
    city: 'czech republic',
    img: './img/czech-republic-prague-castle.jpg',
    name: 'prague castle',
    info: 'a castle complex in Prague, Czech Republic, built in the 9th century. It is the official office of the President of the Czech Republic.  The Bohemian Crown Jewels are kept within a hidden room inside it.According to the Guinness Book of Records, Prague Castle is the largest ancient castle in the world,',
  },
  {
    id: 15,
    city: 'egypt',
    img: './img/egypt-pyramids-giza.jpg',
    name: 'pyramids giza',
    info: 'The Great Pyramid of Giza[a] is the largest Egyptian pyramid and tomb of Fourth Dynasty pharaoh Khufu. Built in the 26th century BC during a period of around 27 years,[3] it is the oldest of the Seven Wonders of the Ancient World, and the only one to remain largely intact. As part of the Giza pyramid complex, .',
  },
  {
    id: 16,
    city: 'england',
    img: './img/england-stonehenge.jpg',
    name: 'stonehenge',
    info: 'Stonehenge is a prehistoric monument on Salisbury Plain in Wiltshire, England, two miles west of Amesbury. It consists of an outer ring of vertical sarsen standing stones, each around 13 feet high, seven feet wide, and weighing around 25 tons, topped by connecting horizontal lintel stones.',
  },
  {
    id: 17,
    city: 'germany',
    img: './img/germany-brandenburg-gate.jpg',
    name: 'brandburg gate',
    info: ' The Brandenburg Gate is one of the most iconic sights in today’s vibrant Berlin. More than just Berlin’s only surviving historical city gate, this site came to symbolise Berlin’s Cold War division into East and West – and, since the fall of the Wall, a reunified Germany. ',
  },
  {
    id: 18,
    city: 'india',
    img: './img/india-taj-mahal.jpg',
    name: 'taj mahal',
    info: ' The Taj Mahal, is an ivory-white marble mausoleum on the right bank of the river Yamuna in the Indian city of Agra. It was commissioned in 1632 by the Mughal emperor Shah Jahan to house the tomb of his favourite wife, Mumtaz Mahal; it also houses the tomb of Shah Jahan himself.',
  },
  {
    id: 19,
    city: 'indonesia',
    img: './img/indonesia-borobudur.jpg',
    name: 'borobudur',
    info: ' Borobudur, also transcribed Barabudur is a 9th-century Mahayana Buddhist temple in Magelang Regency, not far from the town of Muntilan, in Central Java, Indonesia. It is the worlds largest Buddhist temple. The temple consists of nine stacked platforms, six square and three circular, topped by a central dome.',
  },
  {
    id: 20,
    city: 'turkey',
    img: './img/istanbul turkey.jpg',
    name: 'instanbul',
    info: ' Istanbul is a major city in Turkey that straddles Europe and Asia across the Bosphorus Strait. Its Old City reflects cultural influences of the many empires that once ruled here. In the Sultanahmet district, the open-air, Roman-era Hippodrome was for centuries the site of chariot races, and Egyptian obelisks also remain.',
  },
  {
    id: 21,
    city: 'italy',
    img: './img/italy-rome-colosseum.jpg',
    name: 'rome colosseum',
    info: ' The Colosseum is an oval amphitheatre in the centre of the city of Rome, Italy, just east of the Roman Forum. It is the largest ancient amphitheatre ever built, and is still the largest standing amphitheatre in the world today',
  },
  {
    id: 22,
    city: 'jordan',
    img: './img/jordan-petra.jpg',
    name: 'petra',
    info: ' Petra is a famous archaeological site in Jordans southwestern desert. Dating to around 300 B.C., it was the capital of the Nabatean Kingdom. Accessed via a narrow canyon called Al Siq, it contains tombs and temples carved into pink sandstone cliffs, earning its nickname, the "Rose City." . ',
  },
  {
    id: 23,
    city: 'new zealand',
    img: './img/lake tekapo new zealand.jpg',
    name: 'tekapo lake',
    info: ' Lake Tekapo is a small township located at the southern end of the lake of the same name in the inland South Island of New Zealand. It had 558 residents according to the 2018 census, being one of five settlements in the sparsely populated Mackenzie Basin.',
  },
  {
    id: 24,
    city: 'peru',
    img: './img/machu-picchu-peru.jpg',
    name: 'machu picchu',
    info: ' Machu Picchu is an Incan citadel set high in the Andes Mountains in Peru, above the Urubamba River valley. Built in the 15th century and later abandoned, it’s renowned for its sophisticated dry-stone walls that fuse huge blocks without the use of mortar, intriguing buildings that play on astronomical alignments and panoramic views. ',
  },
  {
    id: 25,
    city: 'kenya',
    img: './img/masai mara kenya.jpg',
    name: 'masai mara',
    info: ' Maasai Mara National Reserve is an area of preserved savannah wilderness in southwestern Kenya, along the Tanzanian border. Its animals include lions, cheetahs, elephants, zebras and hippos. Wildebeest traverse its plains during their annual migration. The landscape has grassy plains and rolling hills.',
  },
  {
    id: 26,
    city: 'huawei',
    img: './img/maui hauwia.jpg',
    name: 'maui',
    info: 'Maui is an island in the Central Pacific, part of the Hawaiian archipelago. Sprawling Haleakala National Park encompasses the island’s highest peak, volcanic Haleakala, as well as the pools and waterfalls of Ohe’o Gulch, accessed via scenic, winding Hana Highway.',
  },
  {
    id: 27,
    city: 'fuji',
    img: './img/mount-fuji.jpg',
    name: 'mount fuji',
    info: ' Japan’s Mt. Fuji is an active volcano about 100 kilometers southwest of Tokyo. Commonly called “Fuji-san,” it’s the country’s tallest peak, at 3,776 meters. A pilgrimage site for centuries, it’s considered one of Japan’s 3 sacred mountains, and summit hikes remain a popular activity.',
  },
  {
    id: 28,
    city: 'myanmar',
    img: './img/myanmar-bagan.jpg',
    name: 'bagan',
    info: 'Bagan is an ancient city and a UNESCO World Heritage Site in the Mandalay Region of Myanmar. From the 9th to 13th centuries, the city was the capital of the Bagan Kingdom, the first kingdom that unified the regions that would later constitute Myanmar.',
  },
  {
    id: 29,
    city: 'new york',
    img: './img/new york bridge.jpg',
    name: 'Manhattan bridge',
    info: ' New York Citys crossings date back to 1693, when its first bridge, known as the Kings Bridge, was constructed over Spuyten Duyvil Creek between Manhattan and the Bronx, located in the present-day Kingsbridge neighborhood. The bridge, composed of stone abutments and a timber deck, was demolished in 1917.',
  },
  {
    id: 30,
    city: 'italy',
    img: './img/rome italy.jpg',
    name: 'rome',
    info: ' Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel,possimus!',
  },
  {
    id: 31,
    city: 'new york',
    img: './img/status of liberty newyork.jpg',
    name: 'status of liberty',
    info: ' Statue of Liberty, formally Liberty Enlightening the World, colossal statue on Liberty Island in the Upper New York Bay, U.S., commemorating the friendship of the peoples of the United States and France. Standing 305 feet (93 metres) high including its pedestal.',
  },
  {
    id: 32,
    city: 'sydney',
    img: './img/sydney-opera-house.jpg',
    name: 'opera house',
    info: 'The Sydney Opera House is a multi-venue performing arts centre in Sydney. Located on the banks of Sydney Harbour, it is widely regarded as one of the worlds most famous and distinctive buildings and a masterpiece of 20th century architecture.',
  },
  {
    id: 33,
    city: 'tanzania',
    img: './img/tanzania-mt-kilimanjaro.jpg',
    name: 'mount kilimanjaro',
    info: ' Mount Kilimanjaro is a dormant volcano in Tanzania. It has three volcanic cones: Kibo, Mawenzi, and Shira. It is the highest mountain in Africa and the highest single free-standing mountain above sea level in the world: 5,895 metres above sea level and about 4,900 metres above its plateau base.',
  },
  {
    id: 34,
    city: 'paris',
    img: './img/the-louvre-paris.jpg',
    name: 'louvre',
    info: ' The Louvre, or the Louvre Museum, is the worlds most-visited museum, and a historic landmark in Paris, France. It is the home of some of the best-known works of art, including the Mona Lisa and the Venus de Milo',
  },
  {
    id: 35,
    city: 'dubai',
    img: './img/musemum.jpg',
    name: 'museum future',
    info: ' The Museum of the Future is an exhibition space for innovative and futuristic ideologies, services, and products. Located in the Financial District of Dubai, UAE, the Museum of the Future has three main elements: green hill, building, and void. Founded by the Dubai Future Foundation.',
  },
];
